services:
  db:
    image: postgres:16.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: apisolid
    volumes:
      - ./database:/var/lib/postgresql/data